services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    container_name: api
    restart: always
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      QUARKUS_RABBITMQ_HOST: rabbitmq
      QUARKUS_RABBITMQ_PORT: 5672
      QUARKUS_RABBITMQ_USERNAME: guest
      QUARKUS_RABBITMQ_PASSWORD: guest
      QUARKUS_ANALYTICS_DISABLED: "true"
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
